# -----------------------------------------------------------------------------------------------------------
# A N D R O I D    -    C O N F I G U R A T I O N
# -----------------------------------------------------------------------------------------------------------
# - ndk.environment_variable -> env var name pointing to your local android NDK. 
# - ndk.toolchains_path -> toolchains path for cross compilation in order to target processor architectures. 
# -----------------------------------------------------------------------------------------------------------
# - [targets.name] -> Name of the processor architecture to target. 
# - targets.ar -> Archiver to be used to assemble static libraries compiled from C/C++ code. 
# - targets.linker -> Linker to be used to link Rust code.
# -----------------------------------------------------------------------------------------------------------

[ndk]
environment_variable = "ANDROID_NDK_HOME"
toolchains_path = "/toolchains/llvm/prebuilt/linux-x86_64/bin/"

[targets]

  [targets.armv7-linux-androideabi]
  ar = "arm-linux-androideabi-ar"
  linker = "armv7a-linux-androideabi21-clang"

  [targets.aarch64-linux-android]
  ar = "aarch64-linux-android-ar"
  linker = "aarch64-linux-android21-clang"

  [targets.i686-linux-android]
  ar = "i686-linux-android-ar"
  linker = "i686-linux-android21-clang"

  [targets.x86_64-linux-android]
  ar = "x86_64-linux-android-ar"
  linker = "x86_64-linux-android21-clang"